Tms 6
Fidel9/ShareLane pull request #1
Opened 2021-11-17 13:38 UTC by Fidel9

Добавил новый тест проверка регистрации.

2021-11-17 14:05 UTC, mikola-2 requested changes

2021-11-17 14:05 UTC, mikola-2 commented on src/test/java/SignUpTest.java
> +            public void successfulSignUp() {
Ctrl + Alt + L поможет красиво отформатировать код.

2021-11-17 14:05 UTC, mikola-2 commented on src/test/java/SignUpTest.java
> +        driver.get("https://www.sharelane.com/cgi-bin/register.py?page=1&zip_code=123456");
Тест будет падать, когда разрабы пофиксят ввод зип-кода для шести цифр.

2021-11-17 14:05 UTC, mikola-2 commented on src/test/java/SignUpTest.java
> +        Assert.assertEquals(driver.findElement(By.xpath("//*[@class='error_message']")).getText(),
Получается, что это тест не на успешную регистрацию, а на появление ошибки?

2021-11-19 08:03 UTC, Fidel9 commented
Николай исправил ка вы говорили и запушил. Создал еще один тест и сейчас запушу. У меня будет вопрос по поводу последнего теста и теста с 6 цифрами. Вопрос: я может где то пропустил как должен себя вести тест когда в нем есть баг как в примере с 6 цифрами или последним тестом на проверку пароля. Он должен failed?

2021-11-19 13:07 UTC, merged